[project]
name = "twitchircclient"
version = "0.1.0"
description = "A simple IRC client for connecting to Twitch chat with SSL support and an event-driven system via a dispatcher."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.1",
]
